### ISSUE TITLE
FPC 3.3.1: Doesn't compile

### ISSUE THREAD

**Issue by Raincode** [Xor-el/HashLib4Pascal#7] opened 2019-01-02 20:30 UTC
**Describe the bug**
When selecting [Package] ->[Open Package File (.lpk) ...] -> Select 'HashLib4PascalPackage.lpk' and click [Compile] I get the errors:
```
Compile package HashLib4PascalPackage 3.0: Exit code 1, Errors: 8
HlpAdler32.pas(16,14) Error: No matching implementation for interface method "GetBlockSize:LongInt;" found
HlpAdler32.pas(16,14) Error: No matching implementation for interface method "GetHashSize:LongInt;" found
HlpAdler32.pas(16,14) Error: No matching implementation for interface method "GetBufferSize:LongInt;" found
HlpAdler32.pas(16,14) Error: No matching implementation for interface method "SetBufferSize(LongInt);" found
HlpAdler32.pas(16,14) Error: No matching implementation for interface method "GetBlockSize:LongInt;" found
HlpAdler32.pas(16,14) Error: No matching implementation for interface method "GetHashSize:LongInt;" found
HlpAdler32.pas(16,14) Error: No matching implementation for interface method "GetBufferSize:LongInt;" found
HlpAdler32.pas(16,14) Error: No matching implementation for interface method "SetBufferSize(LongInt);" found
```
My Version:
```
Version #: 2.1.0
FPC Version: 3.3.1
SVN Revision 59976
x86_64-win64-win32/win64
Windows 10
```
Am I doing something wrong?

**Comment by Xor-el** [comment] 2019-01-02 20:37
Hi, thanks for reporting this but unfortunately I cannot reproduce this issue in FPC 3.0, 3.0.2, 3.0.4 and 3.2.0 which I use and support.
Seems like something is broken in FPC trunk.
I suggest you try to use FPC stable version or at least 3.2.0.

**Comment by Raincode** [comment] 2019-01-02 22:39
Yep, 3.2 works... Thanks :)

**Comment by Xor-el** [comment] 2019-01-21 12:34
@Raincode , this has been fixed via https://github.com/Xor-el/HashLib4Pascal/commit/94afe188438ff2a69e942292f7270e950be61b7b
Thanks for reporting it.

**Closed as completed by Xor-el** 2019-01-21 12:34 UTC
